#pragma once

typedef enum {
    STATE_PARSE_INS_READY_TO_PARSE = 1,
    STATE_PARSE_INS_PARSED_INSTRUCTION,
    STATE_PARSE_INS_NEEDS_APPROVAL,
    STATE_PARSE_INS_APPROVED,
    STATE_PARSE_INS_FINISHED_PARSING_ALL_INS,
} parse_tx_ins_state_e;