#pragma once

#include "os.h"

// Keep in sync with
// https://github.com/radixdlt/radixdlt-javascript/blob/main/packages/hardware-ledger/src/_types.ts#L13

// ALL CUSTOM CODES MUST BE IN THIS RANGE: 0xB000 - 0xEFFF
// See below:
// https://github.com/LedgerHQ/nanos-secure-sdk/blob/master/include/errors.h#L45-L52

// Generic identifiers.
enum generic_identifiers_radix {
    ERR_GEN_ID_2C = 0x2c,
    ERR_GEN_ID_2D,
    ERR_GEN_ID_2E,
    ERR_GEN_ID_2F,
    ERR_GEN_ID_30,
    ERR_GEN_ID_31,
    ERR_GEN_ID_32,
    ERR_GEN_ID_33,
    ERR_GEN_ID_34,
    ERR_GEN_ID_35,
    ERR_GEN_ID_36,
    ERR_GEN_ID_37,
    ERR_GEN_ID_38,
    ERR_GEN_ID_39,
    ERR_GEN_ID_3A,
    ERR_GEN_ID_3B,
    ERR_GEN_ID_3C,
    ERR_GEN_ID_3D,
    ERR_GEN_ID_3E,
    ERR_GEN_ID_3F,
    ERR_GEN_ID_40,
    ERR_GEN_ID_41,
    ERR_GEN_ID_42,
    ERR_GEN_ID_43,
    ERR_GEN_ID_44,
    ERR_GEN_ID_45,
    ERR_GEN_ID_46,
    ERR_GEN_ID_47,
    ERR_GEN_ID_48,
    ERR_GEN_ID_49,
    ERR_GEN_ID_4A,
    ERR_GEN_ID_4B,
    ERR_GEN_ID_4C,
    ERR_GEN_ID_4D,
    ERR_GEN_ID_4E,
    ERR_GEN_ID_4F,
    ERR_GEN_ID_50,
    ERR_GEN_ID_51,
    ERR_GEN_ID_52,
    ERR_GEN_ID_53,
    ERR_GEN_ID_54,
    ERR_GEN_ID_55,
    ERR_GEN_ID_56,
    ERR_GEN_ID_57,
    ERR_GEN_ID_58,
    ERR_GEN_ID_59,
    ERR_GEN_ID_5A,
    ERR_GEN_ID_5B,
    ERR_GEN_ID_5C,
    ERR_GEN_ID_5D,
    ERR_GEN_ID_5E,
    ERR_GEN_ID_5F,
    ERR_GEN_ID_60,
    ERR_GEN_ID_61,
    ERR_GEN_ID_62,
    ERR_GEN_ID_63,
    ERR_GEN_ID_64,
    ERR_GEN_ID_65,
    ERR_GEN_ID_66,
    ERR_GEN_ID_67,
    ERR_GEN_ID_68,
    ERR_GEN_ID_69,
    ERR_GEN_ID_6A,
    ERR_GEN_ID_6B,
    ERR_GEN_ID_6C,
    ERR_GEN_ID_6D,
    ERR_GEN_ID_6E,
    ERR_GEN_ID_6F,
    ERR_GEN_ID_70,
    ERR_GEN_ID_71,
    ERR_GEN_ID_72,
    ERR_GEN_ID_73,
    ERR_GEN_ID_74,
    ERR_GEN_ID_75,
    ERR_GEN_ID_76,
    ERR_GEN_ID_77,
    ERR_GEN_ID_78,
    ERR_GEN_ID_79,
    ERR_GEN_ID_7A,
    ERR_GEN_ID_7B,
    ERR_GEN_ID_7C,
    ERR_GEN_ID_7D,
    ERR_GEN_ID_7E,
    ERR_GEN_ID_7F,
    ERR_GEN_ID_80,
    ERR_GEN_ID_81,
    ERR_GEN_ID_82,
    ERR_GEN_ID_83,
    ERR_GEN_ID_84,
    ERR_GEN_ID_85,
    ERR_GEN_ID_86,
    ERR_GEN_ID_87,
    ERR_GEN_ID_88,
    ERR_GEN_ID_89,
    ERR_GEN_ID_8A,
    ERR_GEN_ID_8B,
    ERR_GEN_ID_8C,
    ERR_GEN_ID_8D,
    ERR_GEN_ID_8E,
    ERR_GEN_ID_8F,
    ERR_GEN_ID_90,
    ERR_GEN_ID_91,
    ERR_GEN_ID_92,
    ERR_GEN_ID_93,
    ERR_GEN_ID_94,
    ERR_GEN_ID_95,
    ERR_GEN_ID_96,
    ERR_GEN_ID_97,
    ERR_GEN_ID_98,
    ERR_GEN_ID_99,
    ERR_GEN_ID_9A,
    ERR_GEN_ID_9B,
    ERR_GEN_ID_9C,
    ERR_GEN_ID_9D,
    ERR_GEN_ID_9E,
    ERR_GEN_ID_9F,
    ERR_GEN_ID_A0,
    ERR_GEN_ID_A1,
    ERR_GEN_ID_A2,
    ERR_GEN_ID_A3,
    ERR_GEN_ID_A4,
    ERR_GEN_ID_A5,
    ERR_GEN_ID_A6,
    ERR_GEN_ID_A7,
    ERR_GEN_ID_A8,
    ERR_GEN_ID_A9,
    ERR_GEN_ID_AA,
    ERR_GEN_ID_AB,
    ERR_GEN_ID_AC,
    ERR_GEN_ID_AD,
    ERR_GEN_ID_AE,
    ERR_GEN_ID_AF,
    ERR_GEN_ID_B0,
    ERR_GEN_ID_B1,
    ERR_GEN_ID_B2,
    ERR_GEN_ID_B3,
    ERR_GEN_ID_B4,
    ERR_GEN_ID_B5,
    ERR_GEN_ID_B6,
    ERR_GEN_ID_B7,
    ERR_GEN_ID_B8,
    ERR_GEN_ID_B9,
    ERR_GEN_ID_BA,
    ERR_GEN_ID_BB,
    ERR_GEN_ID_BC,
    ERR_GEN_ID_BD,
    ERR_GEN_ID_BE,
    ERR_GEN_ID_BF,
    ERR_GEN_ID_C0,
    ERR_GEN_ID_C1,
    ERR_GEN_ID_C2,
    ERR_GEN_ID_C3,
    ERR_GEN_ID_C4,
    ERR_GEN_ID_C5,
    ERR_GEN_ID_C6,
    ERR_GEN_ID_C7,
    ERR_GEN_ID_C8,
    ERR_GEN_ID_C9,
    ERR_GEN_ID_CA,
    ERR_GEN_ID_CB,
    ERR_GEN_ID_CC,
    ERR_GEN_ID_CD,
    ERR_GEN_ID_CE,
    ERR_GEN_ID_CF,
    ERR_GEN_ID_D0,
    ERR_GEN_ID_D1,
    ERR_GEN_ID_D2,
    ERR_GEN_ID_D3,
    ERR_GEN_ID_D4,
    ERR_GEN_ID_D5,
    ERR_GEN_ID_D6,
    ERR_GEN_ID_D7,
    ERR_GEN_ID_D8,
    ERR_GEN_ID_D9,
    ERR_GEN_ID_DA,
    ERR_GEN_ID_DB,
    ERR_GEN_ID_DC,
    ERR_GEN_ID_DD,
    ERR_GEN_ID_DE,
    ERR_GEN_ID_DF,
    ERR_GEN_ID_E0,
    ERR_GEN_ID_E1,
    ERR_GEN_ID_E2,
    ERR_GEN_ID_E3,
    ERR_GEN_ID_E4,
    ERR_GEN_ID_E5,
    ERR_GEN_ID_E6,
    ERR_GEN_ID_E7,
    ERR_GEN_ID_E8,
    ERR_GEN_ID_E9,
    ERR_GEN_ID_EA,
    ERR_GEN_ID_EB,
    ERR_GEN_ID_EC,
    ERR_GEN_ID_ED,
    ERR_GEN_ID_EE,
    ERR_GEN_ID_EF,
    ERR_GEN_ID_F0,
    ERR_GEN_ID_F1,
    ERR_GEN_ID_F2,
    ERR_GEN_ID_F3,
    ERR_GEN_ID_F4,
    ERR_GEN_ID_F5,
    ERR_GEN_ID_F6,
    ERR_GEN_ID_F7,
    ERR_GEN_ID_F8,
    ERR_GEN_ID_F9,
    ERR_GEN_ID_FA,
    ERR_GEN_ID_FB,
    ERR_GEN_ID_FC,
    ERR_GEN_ID_FD,
    ERR_GEN_ID_FE,
    ERR_GEN_ID_FF,
};

// Generic subcategories.
#define ERR_GEN_SUB_01 0x0100
#define ERR_GEN_SUB_02 0x0200
#define ERR_GEN_SUB_03 0x0300
#define ERR_GEN_SUB_04 0x0400
#define ERR_GEN_SUB_05 0x0500
#define ERR_GEN_SUB_06 0x0600
#define ERR_GEN_SUB_07 0x0700
#define ERR_GEN_SUB_08 0x0800
#define ERR_GEN_SUB_09 0x0900
#define ERR_GEN_SUB_0D 0x0D00
#define ERR_GEN_SUB_0E 0x0E00

/// $$$$$$$$$$$$$$$$$$$$$$$$$$$$
/// $$   C: Command (CXXX)    $$
/// $$$$$$$$$$$$$$$$$$$$$$$$$$$$
#define ERR_CMD_RANGE 0xC000

#define ERR_CMD_PARSE_APDU (ERR_CMD_RANGE + ERR_GEN_SUB_01)

/**
 * Status word for wrong reponse length (buffer too small or too big).
 */
#define ERR_CMD_PARSE_APDU_RESPONSE_LENGTH (ERR_CMD_PARSE_APDU + ERR_GEN_ID_01)

/// *-------------------------------*
/// |  CMD: GET_VERSION (C3XX)      |
/// *-------------------------------*
#define ERR_CMD_GET_VERSION (ERR_CMD_RANGE + ERR_GEN_SUB_03)

/// *-------------------------------*
/// |  CMD: GET_APP_NAME (C4XX)     |
/// *-------------------------------*
#define ERR_CMD_GET_APP_NAME (ERR_CMD_RANGE + ERR_GEN_SUB_04)

/// *-------------------------------*
/// |  CMD: GET_PUBLIC_KEY (C5XX)   |
/// *-------------------------------*
#define ERR_CMD_GET_PUBLIC_KEY (ERR_CMD_RANGE + ERR_GEN_SUB_05)

#define ERR_CMD_GET_PUBLIC_KEY_FAILED_TO_COMPRESS_KEY (ERR_CMD_GET_PUBLIC_KEY + ERR_GEN_ID_10)

/// *-------------------------------*
/// |  CMD: SIGN_TX (C6XX)          |
/// *-------------------------------*
#define ERR_CMD_SIGN_TX (ERR_CMD_RANGE + ERR_GEN_SUB_06)

// -=: PARSE APDU :=- (C600-C60F)
#define ERR_CMD_SIGN_TX_PARSE_BIP32_PATH_FAILURE        (ERR_CMD_SIGN_TX + ERR_GEN_ID_01)
#define ERR_CMD_SIGN_TX_PARSE_TX_SIZE_FAILURE           (ERR_CMD_SIGN_TX + ERR_GEN_ID_02)
#define ERR_CMD_SIGN_TX_PARSE_INSTRUCTION_COUNT_FAILURE (ERR_CMD_SIGN_TX + ERR_GEN_ID_03)

#define ERR_CMD_SIGN_TX_PARSE_HRP_LEN_FAILURE    (ERR_CMD_SIGN_TX + ERR_GEN_ID_04)
#define ERR_CMD_SIGN_TX_PARSE_HRP_TOO_LONG       (ERR_CMD_SIGN_TX + ERR_GEN_ID_05)
#define ERR_CMD_SIGN_TX_PARSE_HRP_FAILED_TO_READ (ERR_CMD_SIGN_TX + ERR_GEN_ID_06)

#define ERR_CMD_SIGN_TX_UNRECOGNIZED_INSTRUCTION_TYPE  (ERR_CMD_SIGN_TX + ERR_GEN_ID_07)
#define ERR_CMD_SIGN_TX_UNSUPPORTED_INSTRUCTION_TYPE   (ERR_CMD_SIGN_TX + ERR_GEN_ID_08)
#define ERR_CMD_SIGN_TX_FAILED_TO_COMPRESS_MY_KEY      (ERR_CMD_SIGN_TX + ERR_GEN_ID_09)
#define ERR_CMD_SIGN_TX_PARSE_TX_FEE_FROM_SYSCALL_FAIL (ERR_CMD_SIGN_TX + ERR_GEN_ID_0A)

// PARSE SUBSTATE INDEX (C610-C61F)
#define ERR_CMD_SIGN_TX_SUBSTATE_INDEX_PARSE_FAILURE (ERR_CMD_SIGN_TX + ERR_GEN_ID_10)

// PARSE SUBSTATE ID (C620-C62F)
#define ERR_CMD_SIGN_TX_SUBSTATE_ID_HASH_PARSE_FAILURE  (ERR_CMD_SIGN_TX + ERR_GEN_ID_20)
#define ERR_CMD_SIGN_TX_SUBSTATE_ID_INDEX_PARSE_FAILURE (ERR_CMD_SIGN_TX + ERR_GEN_ID_21)

// PARSE SUBSTATE (C630-C66F)
// =:Parse Substate Common:= (C630-C63F) size: 16
#define ERR_CMD_SIGN_TX_UNRECOGNIZED_SUBSTATE_TYPE (ERR_CMD_SIGN_TX + ERR_GEN_ID_30)
#define ERR_CMD_SIGN_TX_UNSUPPORTED_SUBSTATE_TYPE  (ERR_CMD_SIGN_TX + ERR_GEN_ID_31)

#define ERR_CMD_SIGN_TX_PARSE_BYTES_LENGTH_FAILURE (ERR_CMD_SIGN_TX + ERR_GEN_ID_32)
#define ERR_CMD_SIGN_TX_PARSE_BYTES_WRONG_LENGTH   (ERR_CMD_SIGN_TX + ERR_GEN_ID_33)

// Parse Tokens (C640-C64F) size: 16
#define ERR_CMD_SIGN_TX_TOKENS_PARSE_RRI_FAILURE    (ERR_CMD_SIGN_TX + ERR_GEN_ID_40)
#define ERR_CMD_SIGN_TX_TOKENS_PARSE_OWNER_FAILURE  (ERR_CMD_SIGN_TX + ERR_GEN_ID_41)
#define ERR_CMD_SIGN_TX_TOKENS_PARSE_AMOUNT_FAILURE (ERR_CMD_SIGN_TX + ERR_GEN_ID_42)

// Parse Stake (C650-C65F) size: 16
#define ERR_CMD_SIGN_TX_PREPARED_STAKE_PARSE_OWNER_FAILURE    (ERR_CMD_SIGN_TX + ERR_GEN_ID_50)
#define ERR_CMD_SIGN_TX_PREPARED_STAKE_PARSE_DELEGATE_FAILURE (ERR_CMD_SIGN_TX + ERR_GEN_ID_51)
#define ERR_CMD_SIGN_TX_PREPARED_STAKE_PARSE_AMOUNT_FAILURE   (ERR_CMD_SIGN_TX + ERR_GEN_ID_52)

// Parse Unstake (C660-C66F) size: 16
#define ERR_CMD_SIGN_TX_PREPARED_UNSTAKE_PARSE_DELEGATE_FAILURE (ERR_CMD_SIGN_TX + ERR_GEN_ID_60)
#define ERR_CMD_SIGN_TX_PREPARED_UNSTAKE_PARSE_OWNER_FAILURE    (ERR_CMD_SIGN_TX + ERR_GEN_ID_61)
#define ERR_CMD_SIGN_TX_PREPARED_UNSTAKE_PARSE_AMOUNT_FAILURE   (ERR_CMD_SIGN_TX + ERR_GEN_ID_62)

// Parse ShareStake (C670-C67F) size: 16
#define ERR_CMD_SIGN_TX_STAKE_SHARE_PARSE_PUBLIC_KEY_FAILURE (ERR_CMD_SIGN_TX + ERR_GEN_ID_70)
#define ERR_CMD_SIGN_TX_STAKE_SHARE_PARSE_OWNER_FAILURE      (ERR_CMD_SIGN_TX + ERR_GEN_ID_71)
#define ERR_CMD_SIGN_TX_STAKE_SHARE_PARSE_AMOUNT_FAILURE     (ERR_CMD_SIGN_TX + ERR_GEN_ID_72)

// Parse instruction
#define ERR_CMD_SIGN_TX_PARSE_INS_SYSCALL (ERR_CMD_SIGN_TX + ERR_GEN_ID_89)
#define ERR_CMD_SIGN_TX_PARSE_INS_HEADER  (ERR_CMD_SIGN_TX + ERR_GEN_ID_8A)

// Various exceptions during Sign TX flow
#define ERR_CMD_SIGN_TX_DISABLE_MINT_AND_BURN_FLAG_NOT_SET (ERR_CMD_SIGN_TX + ERR_GEN_ID_E0)
#define ERR_CMD_SIGN_TX_ECDSA_SIGN_FAIL                    (ERR_CMD_SIGN_TX + ERR_GEN_ID_E1)
#define ERR_CMD_SIGN_TX_LAST_INSTRUCTION_WAS_NOT_INS_END   (ERR_CMD_SIGN_TX + ERR_GEN_ID_E2)

/// *-------------------------------*
/// |  CMD: SIGN_HASH (C7XX)        |
/// *-------------------------------*
#define ERR_CMD_SIGN_HASH (ERR_CMD_RANGE + ERR_GEN_SUB_07)

#define ERR_CMD_SIGN_HASH_PARSE_HASH_FAILURE_BAD_LENGTH (ERR_CMD_SIGN_HASH + ERR_GEN_ID_01)
#define ERR_CMD_SIGN_HASH_PARSE_HASH_FAILURE_TOO_SHORT  (ERR_CMD_SIGN_HASH + ERR_GEN_ID_02)

#define ERR_CMD_SIGN_HASH_ECDSA_SIGN_FAIL (ERR_CMD_SIGN_HASH + ERR_GEN_ID_E0)

/// *-------------------------------*
/// |  CMD: ECDH (C8XX)             |
/// *-------------------------------*
#define ERR_CMD_ECDH (ERR_CMD_RANGE + ERR_GEN_SUB_08)

#define ERR_CMD_ECDH_OTHER_PARTY_PUBLIC_KEY_PARSE_FAILURE (ERR_CMD_ECDH + ERR_GEN_ID_10)
#define ERR_CMD_ECDH_FAILED_TO_COMPRESS_OTHER_PARTY_KEY   (ERR_CMD_ECDH + ERR_GEN_ID_11)
#define ERR_CMD_ECDH_COMPUTE_SHARED_KEY_FAILURE           (ERR_CMD_ECDH + ERR_GEN_ID_20)

/// $$$$$$$$$$$$$$$$$$$$$$$$$$$$
/// $$   D: Display (DXXX)    $$
/// $$$$$$$$$$$$$$$$$$$$$$$$$$$$
#define ERR_DISPLAY_RANGE 0xD000

#define ERR_DISPLAY (ERR_DISPLAY_RANGE + ERR_GEN_SUB_01)

#define ERR_DISPLAY_BIP32_PATH_FAIL (ERR_DISPLAY + ERR_GEN_ID_01)
#define ERR_DISPLAY_ADDRESS_FAIL    (ERR_DISPLAY + ERR_GEN_ID_02)
#define ERR_DISPLAY_AMOUNT_FAIL     (ERR_DISPLAY + ERR_GEN_ID_03)
#define ERR_DISPLAY_RRI_FAIL        (ERR_DISPLAY + ERR_GEN_ID_04)

/// $$$$$$$$$$$$$$$$$$$$$$$$$$$$
/// $$   E: Exception (EXXX)    $$
/// $$$$$$$$$$$$$$$$$$$$$$$$$$$$
#define ERR_EXCEPTION_RANGE 0xE000

#define ERR_BAD_STATE        (ERR_EXCEPTION_RANGE + ERR_GEN_ID_01)
#define ERR_ASSERTION_FAILED (ERR_EXCEPTION_RANGE + ERR_GEN_ID_02)
#define ERR_FATAL_ERROR      (ERR_EXCEPTION_RANGE + ERR_GEN_ID_03)
